### ISSUE TITLE
Delete DbParam

### ISSUE THREAD

**Issue by BrEaLSxx7** [jalfcolombia/nogal.se#1]
Hace falta un delete cada que haga una consulta a la base de datos 
hay dos posibles soluciones 
1. crear un metodo que borre lo que hay en el array DBParam en datasource 
2. agregar a los metodos query y execute que al terminar la consulta borre lo que hay en el DBParam

**Comment by jalfcolombia** [comment]
My dear apprentice

Thanks for your input, the bug was solved and will be released in version 0.3. Next time I invite you to create your own solution as a contribution to the code. You can ask Johan Serna how you can do it since he made his respective contribution.

Here you can see the proposed solution [commit fec810ce8944a11d215966e2664f0ddc906f69ce](https://github.com/jalfcolombia/nogal.se/commit/fec810ce8944a11d215966e2664f0ddc906f69ce)
